# Created by: Tony Narlock <tony@git-pull.com>
# $FreeBSD$

PORTNAME=	aseprite
PORTVERSION=	1.1.1
CATEGORIES=	graphics

MAINTAINER=	tony@git-pull.com
COMMENT=	Animated sprite editor & pixel art tool 

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		cmake:outsource

USE_GITHUB=	yes
GH_ACCOUNT=	aseprite
GH_PROJECT=	aseprite
GH_TAGNAME=	f3c171d

.include <bsd.port.mk>
